<?php

namespace PHPPlusPlus;

class Compiler {
    /**
     * Compiles the registered routes into a static optimized file
     * This is the heart of the PHP++ performance
     */
    public static function compile($routes) {
        $output = "<?php \n";
        $output .= "// Generated by PHP++ Compiler - Do not edit manually\n";
        $output .= "return [\n";

        foreach ($routes as $method => $items) {
            $output .= "  '$method' => [\n";
            foreach ($items as $pattern => $callback) {
                // Here we start converting dynamic logic to static mapping
                $output .= "    '$pattern' => 'compiled_logic_here',\n";
            }
            $output .= "  ],\n";
        }

        $output .= "];";

        // Save the compiled routes to a cache file
        file_put_contents('cache/routes_compiled.php', $output);
        echo "Successfully compiled routes to O(1) static map! 🚀\n";
    }
}
