<?php

namespace PHPPlusPlus;

class Compiler {
    // The path to the main entry file
    private static $entryFile = 'index.php';

    /**
     * Scans the index.php and compiles routes into a static high-speed file
     */
    public static function build() {
        if (!file_exists(self::$entryFile)) {
            die("Error: Entry file (index.php) not found.");
        }

        $content = file_get_contents(self::$entryFile);
        
        // Regex to find Router::get and Router::post patterns
        // Matches: Router::get('/path', function()...)
        preg_match_all('/Router::(get|post)\(\'([^\']+)\'/', $content, $matches);

        $compiledRoutes = [
            'GET' => [],
            'POST' => []
        ];

        foreach ($matches[1] as $index => $method) {
            $method = strtoupper($method);
            $path = $matches[2][$index];
            
            // Convert path to a static key for O(1) lookup
            $compiledRoutes[$method][$path] = true; 
        }

        self::generateCache($compiledRoutes);
    }

    /**
     * Generates a pure PHP array file for maximum OPcache performance
     */
    private static function generateCache($routes) {
        $cacheDir = 'cache';
        if (!is_dir($cacheDir)) {
            mkdir($cacheDir, 0777, true);
        }

        $code = "<?php\n// Auto-generated by PHP++ Compiler\n// Execution time: " . date('Y-m-d H:i:s') . "\n\n";
        $code .= "return " . var_export($routes, true) . ";";

        file_put_contents($cacheDir . '/routes_compiled.php', $code);
        
        echo "Successfully scanned " . self::$entryFile . " and generated static routes! 🚀\n";
    }
}
